### PR TITLE
48 Mobile: SVG Logo and Gradient

### PR DESCRIPTION
**Pull request by cydgit**

### CODE REVIEW

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , please note that to check this update you'll also need to run grunt in the theme folder.

**Comment by Andreas-Schoenefeldt** [comment]
Hello, this looks good :) - to complete it, can you please
* run grunt and commit also the css changes 
* add the new svg icons attached as zip in the ticket to the repository (the ones there are outdated, if my memory is correct)

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt 
> run grunt and commit also the css changes

done.

> add the new svg icons attached as zip in the ticket to the repository (the ones there are outdated, if my memory is correct)

[logos.zip](https://github.com/Andreas-Schoenefeldt/vt.at-drupal/files/766016/logos.zip)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Olga ( @cydgit ),

what I meant with "add the svg icons" is to also add them to the code. So that it will just work out of the box, if I merge this PR ;) 

Everything else looks good.

Best wishes
Andreas

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt ,

These icons were added to the code 2 months ago:
https://github.com/Andreas-Schoenefeldt/vt.at-drupal/tree/develop/web/themes/vt/css/img
vt-logo_en.svg
vt-logo_de.svg

We are using them, and they are the same as in the attached archive. Should we re-add them?
Please clarify.

**Comment by Andreas-Schoenefeldt** [comment]
ok cool - sorry for the extra loop, I just forgot that I've added them already.

**Pull request merged**
