### PR TITLE
54 Video - enable responsive includes

### PR DESCRIPTION
**Pull request by cydgit**

### CODE REVIEW

**Comment by Andreas-Schoenefeldt** [comment]
HI @cydgit - thi slooks nice, but it will not take the actual entered with and height into account. I entered a few review comments, where I think it can be improved to allow different video sizes :)

Thx a lot!

**Comment by cydgit** [comment]
Hi @Andreas-Schoenefeldt - this is fixed.

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , just to double check here: we use the approach presented in https://coolestguidesontheplanet.com/videodrome/youtube/, but with the calculated padding-bottom, right?
I.e. we use the width and the height only to calculate the padding-bottom, and the width & height of the container will be set to 100% to provide responsiveness.

**Comment by Andreas-Schoenefeldt** [comment]
Thank you.

**Pull request merged**
